In [1]:
import sys
import numpy as np
import anndata as ad
import polars as pl
import pickle
import src as scit

/home/aleksander-work/Skrivbord/pyproject/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import loompy

In [3]:
ds = loompy.connect('private/data/snRNAseq_nomitoribogonads.loom')
Xsp = ds.layer[''].sparse().tocsr()

In [4]:
Xsp.data

array([1., 1., 1., ..., 1., 1., 1.])

In [5]:
ks_ca = ds.ca.keys()
ks_ra = ds.ra.keys()

In [6]:
Xsp.data

array([1., 1., 1., ..., 1., 1., 1.])

In [28]:
rna = ad.AnnData(Xsp.T)

In [29]:
rna

AnnData object with n_obs × n_vars = 18493 × 15293

In [30]:
for k in ks_ca:
    rna.obs[k] = ds.ca[k]
for k in ks_ra:
    rna.var[k] = ds.ra[k]

In [31]:
ks_ca

['CellID',
 'G2M.Score',
 'Phase',
 'S.Score',
 'SCT_snn_res.0.5',
 'SCT_snn_res.0.6',
 'cell',
 'clusters_old',
 'cond',
 'nCount_RNA',
 'nCount_SCT',
 'nFeature_RNA',
 'nFeature_SCT',
 'old.ident',
 'orig.ident',
 'rep',
 'seurat_clusters']

In [33]:
rna.var_names = rna.var['Gene']
rna.var

                          Gene
Gene
l(2)gl                  l(2)gl
CR11023                CR11023
spen                      spen
kis                        kis
Cda5                      Cda5
...                        ...
CR45496                CR45496
CG42577                CG42577
CR34311                CR34311
lncRNA:CR45502  lncRNA:CR45502
CR45948                CR45948

[15293 rows x 1 columns]

In [34]:
anno = pl.read_csv('private/data/emb_nocc_nog_clusters.csv').to_dict()
anno = dict(zip(anno['name'], anno['value']))
anno

{'c_r1_CELL13_N2': 'Epidermis',
 'c_r1_CELL19_N5': 'Muscle somatic',
 'c_r1_CELL23_N2': 'Glia',
 'c_r1_CELL25_N2': 'Midgut',
 'c_r1_CELL41_N4': 'Epidermis',
 'c_r1_CELL44_N3': 'Muscle somatic',
 'c_r1_CELL49_N2': 'Epidermis',
 'c_r1_CELL55_N3': 'Epidermis',
 'c_r1_CELL59_N3': 'Muscle somatic',
 'c_r1_CELL60_N3': 'Neuronal 1',
 'c_r1_CELL63_N4': 'Midgut',
 'c_r1_CELL67_N3': 'Plasmatocytes',
 'c_r1_CELL80_N2': 'Midgut',
 'c_r1_CELL81_N3': 'Sense',
 'c_r1_CELL94_N2': 'Epidermis',
 'c_r1_CELL106_N3': 'Neuronal 2',
 'c_r1_CELL109_N2': 'Amnioserosa',
 'c_r1_CELL114_N5': 'Glia lateral',
 'c_r1_CELL125_N2': 'Yolk',
 'c_r1_CELL131_N4': 'Fat Body',
 'c_r1_CELL135_N3': 'Neuronal 1',
 'c_r1_CELL142_N3': 'Tracheal',
 'c_r1_CELL145_N2': 'Muscle visceral',
 'c_r1_CELL168_N5': 'Midgut',
 'c_r1_CELL177_N2': 'Muscle visceral',
 'c_r1_CELL178_N3': 'Plasmatocytes',
 'c_r1_CELL180_N2': 'Epidermis',
 'c_r1_CELL181_N2': 'Epidermis',
 'c_r1_CELL184_N3': 'Salivary Gland',
 'c_r1_CELL188_N2': 'Neuronal 2',
 'c_r1_CELL191_N3': 'Neuronal 1',
 'c_r1_CELL196_N6': 'Muscle visceral',
 'c_r1_CELL211_N3': 'Epidermis',
 'c_r1_CELL233_N4': 'Neuronal 1',
 'c_r1_CELL238_N2': 'Plasmatocytes',
 'c_r1_CELL269_N2': 'Sense',
 'c_r1_CELL270_N7': 'Muscle somatic',
 'c_r1_CELL291_N2': 'Muscle somatic',
 'c_r1_CELL296_N2': 'Glia',
 'c_r1_CELL305_N2': 'Muscle somatic',
 'c_r1_CELL322_N4': 'Epidermis',
 'c_r1_CELL324_N2': 'Neuronal 1',
 'c_r1_CELL325_N2': 'Tracheal',
 'c_r1_CELL328_N4': 'Epidermis',
 'c_r1_CELL335_N2': 'Epidermis',
 'c_r1_CELL340_N2': 'Midgut',
 'c_r1_CELL350_N3': 'Muscle somatic',
 'c_r1_CELL351_N3': 'Muscle visceral',
 'c_r1_CELL358_N4': 'Epidermis',
 'c_r1_CELL361_N3': 'Fat Body',
 'c_r1_CELL363_N2': 'Epidermis',
 'c_r1_CELL371_N5': 'Neuronal 1',
 'c_r1_CELL375_N2': 'Epidermis',
 'c_r1_CELL390_N2': 'Neuronal 1',
 'c_r1_CELL402_N2': 'Midgut',
 'c_r1_CELL412_N2': 'Glia lateral',
 'c_r1_CELL414_N3': 'Muscle visceral',
 'c_r1_CELL421_N3': 'Neuronal 1',
 'c_r1_CELL422_N3': 'Neuronal 2',
 'c_r1_CELL432_N2': 'Yolk',
 'c_r1_CELL435_N5': 'Muscle visceral',
 'c_r1_CELL439_N5': 'Neuronal 1',
 'c_r1_CELL479_N3': 'Muscle somatic',
 'c_r1_CELL488_N2': 'Midgut',
 'c_r1_CELL495_N2': 'Neuronal 1',
 'c_r1_CELL501_N3': 'Plasmatocytes',
 'c_r1_CELL504_N6': 'Midgut',
 'c_r1_CELL506_N2': 'Neuronal 1',
 'c_r1_CELL510_N3': 'Glia',
 'c_r1_CELL516_N3': 'Neuronal 1',
 'c_r1_CELL521_N4': 'Fat Body',
 'c_r1_CELL528_N2': 'Epidermis',
 'c_r1_CELL549_N2': 'Yolk',
 'c_r1_CELL553_N2': 'Glia',
 'c_r1_CELL560_N5': 'Tracheal',
 'c_r1_CELL569_N4': 'Neuronal 1',
 'c_r1_CELL579_N2': 'Neuronal 1',
 'c_r1_CELL583_N2': 'Muscle somatic',
 'c_r1_CELL588_N2': 'Epidermis',
 'c_r1_CELL599_N4': 'Epidermis',
 'c_r1_CELL606_N2': 'Yolk',
 'c_r1_CELL611_N3': 'Tracheal',
 'c_r1_CELL623_N2': 'Midgut',
 'c_r1_CELL624_N3': 'Epidermis',
 'c_r1_CELL625_N4': 'Yolk',
 'c_r1_CELL628_N3': 'Muscle somatic',
 'c_r1_CELL637_N4': 'Epidermis',
 'c_r1_CELL647_N8': 'Muscle somatic',
 'c_r1_CELL654_N2': 'Epidermis',
 'c_r1_CELL663_N3': 'Epidermis',
 'c_r1_CELL664_N3': 'Neuronal 1',
 'c_r1_CELL669_N2': 'Epidermis',
 'c_r1_CELL674_N3': 'Muscle somatic',
 'c_r1_CELL676_N2': 'Neuronal 1',
 'c_r1_CELL691_N2': 'Muscle visceral',
 'c_r1_CELL698_N4': 'Neuronal 1',
 'c_r1_CELL709_N8': 'Epidermis',
 'c_r1_CELL719_N2': 'Plasmatocytes',
 'c_r1_CELL721_N3': 'Neuronal 1',
 'c_r1_CELL722_N3': 'Tracheal',
 'c_r1_CELL726_N3': 'Midgut',
 'c_r1_CELL730_N3': 'Fat Body',
 'c_r1_CELL731_N5': 'Tracheal',
 'c_r1_CELL736_N2': 'Tracheal',
 'c_r1_CELL737_N4': 'Epidermis',
 'c_r1_CELL740_N3': 'Epidermis',
 'c_r1_CELL741_N2': 'Midgut',
 'c_r1_CELL746_N3': 'Muscle visceral',
 'c_r1_CELL747_N2': 'Neuronal 1',
 'c_r1_CELL749_N2': 'Fat Body',
 'c_r1_CELL753_N2': 'Neuronal 1',
 'c_r1_CELL755_N2': 'Neuronal 1',
 'c_r1_CELL761_N2': 'Neuronal 2',
 'c_r1_CELL769_N5': 'Neuronal 1',
 'c_r1_CELL775_N4': 'Neuronal 1',
 'c_r1_CELL783_N4': 'Sense',
 'c_r1_CELL790_N2': 'Neuronal 1',
 'c_r1_CELL796_N3': 'Epidermis',
 'c_r1_CELL824_N2': 'Neuronal 1',
 'c_r1_CELL828_N3': 'Neuronal 1',
 'c_r1_CELL833_N2': 'Midgut',
 'c_r1_CELL842_N5': 'Fat Body',
 'c_r1_CELL843_N2': 'Neuronal 1',
 'c_r1_CELL847_N5': 'Epidermis',
 'c_r1_CELL849_N2': 'Epidermis',
 'c_r1_CELL850_N4': 'Sense',
 'c_r1_CELL856_N4': 'Yolk',
 'c_r1_CELL867_N2': 'Epidermis',
 'c_r1_CELL869_N3': 'Midgut',
 'c_r1_CELL879_N2': 'Epidermis',
 'c_r1_CELL886_N6': 'Muscle visceral',
 'c_r1_CELL887_N3': 'Muscle visceral',
 'c_r1_CELL888_N4': 'Neuronal 1',
 'c_r1_CELL903_N3': 'Neuronal 1',
 'c_r1_CELL911_N3': 'Muscle somatic',
 'c_r1_CELL913_N2': 'Muscle somatic',
 'c_r1_CELL936_N2': 'Neuronal 1',
 'c_r1_CELL938_N2': 'Epidermis',
 'c_r1_CELL940_N3': 'Neuronal 1',
 'c_r1_CELL941_N2': 'Epidermis',
 'c_r1_CELL949_N3': 'Epidermis',
 'c_r1_CELL953_N3': 'Neuronal 1',
 'c_r1_CELL959_N2': 'Bristle',
 'c_r1_CELL979_N5': 'Midgut',
 'c_r1_CELL986_N2': 'Epidermis',
 'c_r1_CELL993_N5': 'Neuronal 1',
 'c_r1_CELL997_N4': 'Muscle somatic',
 'c_r1_CELL998_N3': 'Epidermis',
 'c_r1_CELL1000_N3': 'Neuronal 1',
 'c_r1_CELL1001_N3': 'Muscle somatic',
 'c_r1_CELL1003_N2': 'Neuronal 2',
 'c_r1_CELL1008_N5': 'Neuronal 1',
 'c_r1_CELL1012_N3': 'Tracheal',
 'c_r1_CELL1014_N6': 'Muscle somatic',
 'c_r1_CELL1023_N2': 'Muscle somatic',
 'c_r1_CELL1025_N4': 'Muscle visceral',
 'c_r1_CELL1028_N2': 'Epidermis',
 'c_r1_CELL1038_N2': 'Sense',
 'c_r1_CELL1039_N2': 'Epidermis',
 'c_r1_CELL1053_N4': 'Salivary Gland',
 'c_r1_CELL1055_N3': 'Tracheal',
 'c_r1_CELL1067_N3': 'Muscle somatic',
 'c_r1_CELL1068_N6': 'Fat Body',
 'c_r1_CELL1073_N7': 'Neuronal 1',
 'c_r1_CELL1076_N2': 'Epidermis',
 'c_r1_CELL1080_N5': 'Muscle somatic',
 'c_r1_CELL1098_N2': 'Epidermis',
 'c_r1_CELL1103_N5': 'Epidermis',
 'c_r1_CELL1108_N3': 'Muscle somatic',
 'c_r1_CELL1110_N2': 'Plasmatocytes',
 'c_r1_CELL1119_N4': 'Muscle somatic',
 'c_r1_CELL1120_N2': 'Fat Body',
 'c_r1_CELL1130_N4': 'Epidermis',
 'c_r1_CELL1131_N3': 'Yolk',
 'c_r1_CELL1140_N2': 'Epidermis',
 'c_r1_CELL1145_N2': 'Yolk',
 'c_r1_CELL1150_N2': 'Muscle visceral',
 'c_r1_CELL1151_N2': 'Muscle somatic',
 'c_r1_CELL1161_N3': 'Plasmatocytes',
 'c_r1_CELL1164_N6': 'Epidermis',
 'c_r1_CELL1166_N2': 'Sense',
 'c_r1_CELL1167_N2': 'Epidermis',
 'c_r1_CELL1175_N4': 'Epidermis head',
 'c_r1_CELL1176_N2': 'Epidermis',
 'c_r1_CELL1180_N3': 'Neuronal 1',
 'c_r1_CELL1186_N4': 'Muscle visceral',
 'c_r1_CELL1194_N2': 'Epidermis',
 'c_r1_CELL1198_N4': 'Glia',
 'c_r1_CELL1207_N2': 'Epidermis',
 'c_r1_CELL1217_N2': 'Epidermis',
 'c_r1_CELL1227_N2': 'Muscle somatic',
 'c_r1_CELL1228_N2': 'Fat Body',
 'c_r1_CELL1229_N3': 'Plasmatocytes',
 'c_r1_CELL1253_N2': 'Epidermis',
 'c_r1_CELL1263_N3': 'Muscle somatic',
 'c_r1_CELL1267_N2': 'Epidermis',
 'c_r1_CELL1271_N3': 'Epidermis',
 'c_r1_CELL1272_N2': 'Neuronal 2',
 'c_r1_CELL1278_N5': 'Epidermis',
 'c_r1_CELL1287_N8': 'Epidermis',
 'c_r1_CELL1291_N2': 'Muscle somatic',
 'c_r1_CELL1310_N4': 'Yolk',
 'c_r1_CELL1311_N6': 'Muscle visceral',
 'c_r1_CELL1312_N2': 'Muscle somatic',
 'c_r1_CELL1313_N2': 'Neuronal 1',
 'c_r1_CELL1320_N2': 'Glia',
 'c_r1_CELL1321_N2': 'Muscle somatic',
 'c_r1_CELL1323_N3': 'Muscle somatic',
 'c_r1_CELL1329_N4': 'Epidermis',
 'c_r1_CELL1330_N2': 'Muscle somatic',
 'c_r1_CELL1334_N6': 'Plasmatocytes',
 'c_r1_CELL1335_N4': 'Epidermis',
 'c_r1_CELL1336_N3': 'Epidermis',
 'c_r1_CELL1338_N5': 'Yolk',
 'c_r1_CELL1340_N2': 'Muscle somatic',
 'c_r1_CELL1345_N3': 'Fat Body',
 'c_r1_CELL1347_N2': 'Epidermis',
 'c_r1_CELL1349_N3': 'Epidermis',
 'c_r1_CELL1353_N7': 'Yolk',
 'c_r1_CELL1367_N2': 'Epidermis',
 'c_r1_CELL1378_N4': 'Midgut',
 'c_r1_CELL1381_N2': 'Bristle',
 'c_r1_CELL1389_N1': 'Epidermis',
 'c_r1_CELL1396_N6': 'Neuronal 1',
 'c_r1_CELL1408_N2': 'Epidermis',
 'c_r1_CELL1414_N3': 'Epidermis',
 'c_r1_CELL1422_N6': 'Epidermis',
 'c_r1_CELL1424_N2': 'Yolk',
 'c_r1_CELL1426_N3': 'Fat Body',
 'c_r1_CELL1428_N2': 'Muscle somatic',
 'c_r1_CELL1438_N2': 'Neuronal 1',
 'c_r1_CELL1444_N5': 'Neuronal 1',
 'c_r1_CELL1453_N4': 'Epidermis',
 'c_r1_CELL1456_N4': 'Muscle visceral',
 'c_r1_CELL1458_N2': 'Neuronal 1',
 'c_r1_CELL1461_N2': 'Neuronal 1',
 'c_r1_CELL1470_N2': 'Tracheal',
 'c_r1_CELL1474_N2': 'Epidermis',
 'c_r1_CELL1475_N4': 'Neuronal 2',
 'c_r1_CELL1482_N2': 'Muscle somatic',
 'c_r1_CELL1492_N2': 'Epidermis',
 'c_r1_CELL1495_N5': 'Glia lateral',
 'c_r1_CELL1498_N5': 'Muscle visceral',
 'c_r1_CELL1499_N2': 'Neuronal 1',
 'c_r1_CELL1501_N5': 'Muscle somatic',
 'c_r1_CELL1502_N3': 'Fat Body',
 'c_r1_CELL1519_N3': 'Neuronal 2',
 'c_r1_CELL1522_N3': 'Yolk',
 'c_r1_CELL1525_N3': 'Midgut',
 'c_r1_CELL1527_N2': 'Neuronal 1',
 'c_r1_CELL1532_N1': 'Epidermis',
 'c_r1_CELL1534_N2': 'Epidermis',
 'c_r1_CELL1540_N4': 'Neuronal 1',
 'c_r1_CELL1543_N3': 'Salivary Gland',
 'c_r1_CELL1553_N3': 'Fat Body',
 'c_r1_CELL1560_N2': 'Midgut',
 'c_r1_CELL1561_N2': 'Epidermis',
 'c_r1_CELL1563_N3': 'Glia',
 'c_r1_CELL1572_N4': 'Epidermis',
 'c_r1_CELL1582_N3': 'Fat Body',
 'c_r1_CELL1583_N2': 'Sense',
 'c_r1_CELL1585_N2': 'Yolk',
 'c_r1_CELL1589_N2': 'Glia lateral',
 'c_r1_CELL1607_N3': 'Midgut',
 'c_r1_CELL1615_N6': 'Yolk',
 'c_r1_CELL1618_N2': 'Midgut',
 'c_r1_CELL1634_N2': 'Tracheal',
 'c_r1_CELL1638_N3': 'Tracheal',
 'c_r1_CELL1639_N2': 'Salivary Gland',
 'c_r1_CELL1640_N5': 'Epidermis',
 'c_r1_CELL1676_N3': 'Tracheal',
 'c_r1_CELL1680_N4': 'Midgut',
 'c_r1_CELL1682_N4': 'Epidermis',
 'c_r1_CELL1692_N5': 'Epidermis',
 'c_r1_CELL1697_N4': 'Epidermis',
 'c_r1_CELL1716_N4': 'Neuronal 1',
 'c_r1_CELL1722_N4': 'Muscle visceral',
 'c_r1_CELL1726_N3': 'Yolk',
 'c_r1_CELL1727_N2': 'Epidermis',
 'c_r1_CELL1732_N2': 'Neuronal 1',
 'c_r1_CELL1747_N2': 'Neuronal 1',
 'c_r1_CELL1750_N3': 'Epidermis',
 'c_r1_CELL1753_N3': 'Epidermis',
 'c_r1_CELL1759_N3': 'Epidermis',
 'c_r1_CELL1761_N2': 'Yolk',
 'c_r1_CELL1772_N2': 'Muscle somatic',
 'c_r1_CELL1778_N5': 'Neuronal 2',
 'c_r1_CELL1780_N2': 'Muscle somatic',
 'c_r1_CELL1781_N5': 'Epidermis',
 'c_r1_CELL1787_N3': 'Plasmatocytes',
 'c_r1_CELL1789_N3': 'Epidermis',
 'c_r1_CELL1792_N4': 'Epidermis',
 'c_r1_CELL1800_N4': 'Yolk',
 'c_r1_CELL1803_N3': 'Epidermis',
 'c_r1_CELL1808_N4': 'Yolk',
 'c_r1_CELL1812_N3': 'Neuronal 1',
 'c_r1_CELL1814_N2': 'Midgut',
 'c_r1_CELL1817_N3': 'Epidermis',
 'c_r1_CELL1833_N5': 'Yolk',
 'c_r1_CELL1861_N3': 'Epidermis',
 'c_r1_CELL1869_N2': 'Epidermis',
 'c_r1_CELL1873_N2': 'Bristle',
 'c_r1_CELL1875_N3': 'Epidermis',
 'c_r1_CELL1878_N3': 'Sense',
 'c_r1_CELL1883_N2': 'Neuronal 1',
 'c_r1_CELL1890_N2': 'Tracheal',
 'c_r1_CELL1906_N6': 'Bristle',
 'c_r1_CELL1910_N2': 'Salivary Gland',
 'c_r1_CELL1918_N3': 'Tracheal',
 'c_r1_CELL1925_N4': 'Tracheal',
 'c_r1_CELL1930_N4': 'Epidermis',
 'c_r1_CELL1942_N2': 'Epidermis',
 'c_r1_CELL1954_N2': 'Neuronal 2',
 'c_r1_CELL1974_N4': 'Plasmatocytes',
 'c_r1_CELL1976_N2': 'Epidermis',
 'c_r1_CELL1983_N6': 'Muscle somatic',
 'c_r1_CELL1989_N3': 'Muscle somatic',
 'c_r1_CELL1992_N3': 'Fat Body',
 'c_r1_CELL2000_N2': 'Epidermis',
 'c_r1_CELL2004_N2': 'Epidermis',
 'c_r1_CELL2009_N2': 'Yolk',
 'c_r1_CELL2010_N3': 'Tracheal',
 'c_r1_CELL2030_N3': 'Neuronal 1',
 'c_r1_CELL2032_N3': 'Amnioserosa',
 'c_r1_CELL2034_N4': 'Epidermis',
 'c_r1_CELL2035_N2': 'Epidermis',
 'c_r1_CELL2043_N2': 'Sense',
 'c_r1_CELL2047_N2': 'Epidermis',
 'c_r1_CELL2051_N2': 'Muscle somatic',
 'c_r1_CELL2052_N6': 'Epidermis',
 'c_r1_CELL2053_N3': 'Epidermis',
 'c_r1_CELL2055_N3': 'Epidermis',
 'c_r1_CELL2084_N3': 'Epidermis',
 'c_r1_CELL2096_N3': 'Epidermis',
 'c_r1_CELL2098_N2': 'Muscle somatic',
 'c_r1_CELL2099_N3': 'Neuronal 1',
 'c_r1_CELL2111_N2': 'Neuronal 1',
 'c_r1_CELL2114_N2': 'Sense',
 'c_r1_CELL2120_N2': 'Epidermis',
 'c_r1_CELL2133_N2': 'Glia',
 'c_r1_CELL2135_N5': 'Neuronal 1',
 'c_r1_CELL2147_N2': 'Epidermis',
 'c_r1_CELL2150_N3': 'Tracheal',
 'c_r1_CELL2152_N2': 'Epidermis',
 'c_r1_CELL2153_N3': 'Epidermis',
 'c_r1_CELL2157_N4': 'Midgut',
 'c_r1_CELL2165_N2': 'Muscle somatic',
 'c_r1_CELL2166_N3': 'Midgut',
 'c_r1_CELL2168_N2': 'Epidermis',
 'c_r1_CELL2189_N3': 'Yolk',
 'c_r1_CELL2194_N2': 'Muscle somatic',
 'c_r1_CELL2196_N4': 'Neuronal 2',
 'c_r1_CELL2199_N3': 'Epidermis',
 'c_r1_CELL2210_N2': 'Neuronal 1',
 'c_r1_CELL2211_N2': 'Neuronal 1',
 'c_r1_CELL2226_N3': 'Midgut',
 'c_r1_CELL2227_N2': 'Salivary Gland',
 'c_r1_CELL2230_N2': 'Neuronal 1',
 'c_r1_CELL2235_N2': 'Neuronal 1',
 'c_r1_CELL2248_N6': 'Glia',
 'c_r1_CELL2251_N4': 'Epidermis',
 'c_r1_CELL2257_N3': 'Epidermis head',
 'c_r1_CELL2267_N3': 'Tracheal',
 'c_r1_CELL2270_N3': 'Epidermis',
 'c_r1_CELL2271_N4': 'Muscle somatic',
 'c_r1_CELL2273_N2': 'Epidermis',
 'c_r1_CELL2276_N6': 'Neuronal 1',
 'c_r1_CELL2278_N2': 'Yolk',
 'c_r1_CELL2280_N2': 'Epidermis',
 'c_r1_CELL2281_N6': 'Muscle somatic',
 'c_r1_CELL2283_N5': 'Epidermis',
 'c_r1_CELL2290_N4': 'Glia',
 'c_r1_CELL2294_N2': 'Glia',
 'c_r1_CELL2305_N2': 'Epidermis',
 'c_r1_CELL2306_N2': 'Plasmatocytes',
 'c_r1_CELL2310_N5': 'Epidermis',
 'c_r1_CELL2311_N2': 'Muscle somatic',
 'c_r1_CELL2319_N2': 'Neuronal 2',
 'c_r1_CELL2321_N3': 'Muscle somatic',
 'c_r1_CELL2327_N4': 'Epidermis',
 'c_r1_CELL2333_N5': 'Muscle somatic',
 'c_r1_CELL2337_N2': 'Epidermis',
 'c_r1_CELL2354_N3': 'Epidermis',
 'c_r1_CELL2356_N2': 'Muscle somatic',
 'c_r1_CELL2365_N3': 'Epidermis',
 'c_r1_CELL2370_N4': 'Neuronal 1',
 'c_r1_CELL2378_N2': 'Muscle somatic',
 'c_r1_CELL2386_N4': 'Neuronal 2',
 'c_r1_CELL2400_N4': 'Muscle visceral',
 'c_r1_CELL2401_N3': 'Neuronal 1',
 'c_r1_CELL2407_N4': 'Plasmatocytes',
 'c_r1_CELL2412_N3': 'Muscle somatic',
 'c_r1_CELL2413_N3': 'Muscle somatic',
 'c_r1_CELL2432_N4': 'Epidermis',
 'c_r1_CELL2465_N2': 'Neuronal 1',
 'c_r1_CELL2467_N2': 'Epidermis',
 'c_r1_CELL2472_N6': 'Plasmatocytes',
 'c_r1_CELL2477_N5': 'Neuronal 1',
 'c_r1_CELL2488_N2': 'Epidermis',
 'c_r1_CELL2489_N3': 'Epidermis',
 'c_r1_CELL2499_N1': 'Plasmatocytes',
 'c_r1_CELL2500_N2': 'Neuronal 1',
 'c_r1_CELL2506_N3': 'Neuronal 1',
 'c_r1_CELL2530_N2': 'Plasmatocytes',
 'c_r1_CELL2536_N2': 'Midgut',
 'c_r1_CELL2540_N3': 'Neuronal 1',
 'c_r1_CELL2542_N3': 'Fat Body',
 'c_r1_CELL2569_N2': 'Epidermis',
 'c_r1_CELL2572_N2': 'Plasmatocytes',
 'c_r1_CELL2577_N2': 'Neuronal 1',
 'c_r1_CELL2578_N3': 'Fat Body',
 'c_r1_CELL2585_N3': 'Neuronal 1',
 'c_r1_CELL2595_N2': 'Neuronal 1',
 'c_r1_CELL2597_N3': 'Yolk',
 'c_r1_CELL2601_N6': 'Muscle somatic',
 'c_r1_CELL2616_N4': 'Epidermis',
 'c_r1_CELL2620_N2': 'Epidermis head',
 'c_r1_CELL2626_N3': 'Muscle somatic',
 'c_r1_CELL2633_N5': 'Neuronal 1',
 'c_r1_CELL2639_N4': 'Neuronal 1',
 'c_r1_CELL2643_N3': 'Muscle somatic',
 'c_r1_CELL2650_N3': 'Fat Body',
 'c_r1_CELL2651_N6': 'Epidermis',
 'c_r1_CELL2658_N4': 'Glia',
 'c_r1_CELL2669_N3': 'Epidermis',
 'c_r1_CELL2674_N2': 'Glia',
 'c_r1_CELL2677_N4': 'Epidermis',
 'c_r1_CELL2679_N3': 'Plasmatocytes',
 'c_r1_CELL2685_N4': 'Fat Body',
 'c_r1_CELL2701_N4': 'Neuronal 2',
 'c_r1_CELL2711_N2': 'Sense',
 'c_r1_CELL2726_N2': 'Epidermis',
 'c_r1_CELL2735_N3': 'Fat Body',
 'c_r1_CELL2737_N2': 'Neuronal 1',
 'c_r1_CELL2741_N3': 'Neuronal 1',
 'c_r1_CELL2745_N4': 'Neuronal 1',
 'c_r1_CELL2749_N5': 'Neuronal 2',
 'c_r1_CELL2772_N3': 'Epidermis',
 'c_r1_CELL2777_N6': 'Fat Body',
 'c_r1_CELL2786_N4': 'Muscle somatic',
 'c_r1_CELL2794_N4': 'Fat Body',
 'c_r1_CELL2806_N5': 'Yolk',
 'c_r1_CELL2821_N5': 'Plasmatocytes',
 'c_r1_CELL2824_N2': 'Neuronal 1',
 'c_r1_CELL2828_N5': 'Bristle',
 'c_r1_CELL2829_N2': 'Fat Body',
 'c_r1_CELL2837_N3': 'Neuronal 1',
 'c_r1_CELL2839_N2': 'Fat Body',
 'c_r1_CELL2845_N3': 'Midgut',
 'c_r1_CELL2858_N3': 'Neuronal 2',
 'c_r1_CELL2864_N2': 'Plasmatocytes',
 'c_r1_CELL2870_N2': 'Yolk',
 'c_r1_CELL2878_N3': 'Neuronal 1',
 'c_r1_CELL2884_N3': 'Tracheal',
 'c_r1_CELL2888_N2': 'Epidermis',
 'c_r1_CELL2889_N3': 'Epidermis',
 'c_r1_CELL2893_N2': 'Bristle',
 'c_r1_CELL2897_N3': 'Yolk',
 'c_r1_CELL2902_N2': 'Epidermis',
 'c_r1_CELL2908_N3': 'Muscle somatic',
 'c_r1_CELL2916_N2': 'Muscle visceral',
 'c_r1_CELL2922_N9': 'Neuronal 1',
 'c_r1_CELL2925_N3': 'Sense',
 'c_r1_CELL2930_N3': 'Epidermis',
 'c_r1_CELL2931_N2': 'Neuronal 2',
 'c_r1_CELL2939_N2': 'Plasmatocytes',
 'c_r1_CELL2945_N3': 'Epidermis',
 'c_r1_CELL2946_N4': 'Fat Body',
 'c_r1_CELL2953_N2': 'Yolk',
 'c_r1_CELL2956_N3': 'Yolk',
 'c_r1_CELL2961_N2': 'Yolk',
 'c_r1_CELL2963_N3': 'Muscle somatic',
 'c_r1_CELL2968_N3': 'Neuronal 1',
 'c_r1_CELL2983_N2': 'Fat Body',
 'c_r1_CELL2985_N3': 'Epidermis',
 'c_r1_CELL2994_N4': 'Fat Body',
 'c_r1_CELL2996_N2': 'Neuronal 1',
 'c_r1_CELL3000_N2': 'Epidermis',
 'c_r1_CELL3003_N2': 'Epidermis',
 'c_r1_CELL3009_N5': 'Sense',
 'c_r1_CELL3012_N3': 'Neuronal 1',
 'c_r1_CELL3017_N4': 'Neuronal 1',
 'c_r1_CELL3018_N3': 'Glia',
 'c_r1_CELL3019_N1': 'Epidermis',
 'c_r1_CELL3020_N2': 'Muscle somatic',
 'c_r1_CELL3023_N4': 'Midgut',
 'c_r1_CELL3028_N2': 'Fat Body',
 'c_r1_CELL3029_N5': 'Neuronal 1',
 'c_r1_CELL3032_N3': 'Neuronal 1',
 'c_r1_CELL3042_N3': 'Muscle somatic',
 'c_r1_CELL3044_N2': 'Muscle somatic',
 'c_r1_CELL3046_N3': 'Epidermis',
 'c_r1_CELL3057_N3': 'Muscle somatic',
 'c_r1_CELL3058_N3': 'Epidermis',
 'c_r1_CELL3061_N2': 'Neuronal 1',
 'c_r1_CELL3066_N4': 'Epidermis',
 'c_r1_CELL3069_N2': 'Neuronal 1',
 'c_r1_CELL3075_N4': 'Epidermis',
 'c_r1_CELL3083_N4': 'Neuronal 1',
 'c_r1_CELL3086_N3': 'Midgut',
 'c_r1_CELL3087_N2': 'Muscle somatic',
 'c_r1_CELL3097_N2': 'Neuronal 1',
 'c_r1_CELL3102_N4': 'Epidermis',
 'c_r1_CELL3121_N3': 'Muscle somatic',
 'c_r1_CELL3123_N3': 'Glia',
 'c_r1_CELL3133_N6': 'Neuronal 1',
 'c_r1_CELL3136_N3': 'Muscle visceral',
 'c_r1_CELL3152_N3': 'Epidermis',
 'c_r1_CELL3157_N2': 'Neuronal 1',
 'c_r1_CELL3178_N4': 'Neuronal 1',
 'c_r1_CELL3182_N5': 'Glia',
 'c_r1_CELL3189_N2': 'Yolk',
 'c_r1_CELL3191_N4': 'Tracheal',
 'c_r1_CELL3196_N2': 'Sense',
 'c_r1_CELL3205_N2': 'Tracheal',
 'c_r1_CELL3207_N3': 'Muscle somatic',
 'c_r1_CELL3211_N4': 'Yolk',
 'c_r1_CELL3217_N3': 'Epidermis',
 'c_r1_CELL3220_N3': 'Plasmatocytes',
 'c_r1_CELL3221_N2': 'Yolk',
 'c_r1_CELL3223_N3': 'Midgut',
 'c_r1_CELL3234_N2': 'Neuronal 1',
 'c_r1_CELL3236_N3': 'Epidermis',
 'c_r1_CELL3243_N3': 'Midgut',
 'c_r1_CELL3244_N3': 'Plasmatocytes',
 'c_r1_CELL3245_N7': 'Neuronal 1',
 'c_r1_CELL3250_N3': 'Neuronal 1',
 'c_r1_CELL3252_N3': 'Epidermis',
 'c_r1_CELL3253_N3': 'Tracheal',
 'c_r1_CELL3256_N3': 'Sense',
 'c_r1_CELL3262_N5': 'Muscle visceral',
 'c_r1_CELL3266_N5': 'Glia',
 'c_r1_CELL3277_N4': 'Epidermis',
 'c_r1_CELL3298_N2': 'Epidermis',
 'c_r1_CELL3302_N2': 'Neuronal 2',
 'c_r1_CELL3303_N2': 'Epidermis',
 'c_r1_CELL3306_N2': 'Amnioserosa',
 'c_r1_CELL3327_N2': 'Sense',
 'c_r1_CELL3330_N3': 'Muscle visceral',
 'c_r1_CELL3331_N2': 'Epidermis',
 'c_r1_CELL3339_N3': 'Muscle somatic',
 'c_r1_CELL3340_N3': 'Muscle visceral',
 'c_r1_CELL3353_N3': 'Neuronal 1',
 'c_r1_CELL3364_N3': 'Salivary Gland',
 'c_r1_CELL3379_N2': 'Epidermis',
 'c_r1_CELL3384_N3': 'Neuronal 1',
 'c_r1_CELL3385_N2': 'Neuronal 1',
 'c_r1_CELL3390_N2': 'Epidermis',
 'c_r1_CELL3396_N2': 'Neuronal 1',
 'c_r1_CELL3397_N4': 'Epidermis',
 'c_r1_CELL3405_N2': 'Epidermis',
 'c_r1_CELL3407_N2': 'Bristle',
 'c_r1_CELL3411_N4': 'Yolk',
 'c_r1_CELL3414_N2': 'Neuronal 1',
 'c_r1_CELL3416_N2': 'Yolk',
 'c_r1_CELL3428_N2': 'Muscle somatic',
 'c_r1_CELL3429_N5': 'Epidermis',
 'c_r1_CELL3434_N2': 'Muscle somatic',
 'c_r1_CELL3447_N2': 'Epidermis',
 'c_r1_CELL3448_N3': 'Yolk',
 'c_r1_CELL3458_N2': 'Muscle somatic',
 'c_r1_CELL3461_N3': 'Muscle somatic',
 'c_r1_CELL3463_N7': 'Midgut',
 'c_r1_CELL3478_N2': 'Epidermis',
 'c_r1_CELL3479_N4': 'Midgut',
 'c_r1_CELL3482_N3': 'Epidermis',
 'c_r1_CELL3486_N2': 'Tracheal',
 'c_r1_CELL3489_N3': 'Midgut',
 'c_r1_CELL3493_N2': 'Muscle visceral',
 'c_r1_CELL3515_N5': 'Muscle somatic',
 'c_r1_CELL3520_N2': 'Neuronal 1',
 'c_r1_CELL3524_N5': 'Bristle',
 'c_r1_CELL3526_N2': 'Muscle visceral',
 'c_r1_CELL3533_N4': 'Epidermis',
 'c_r1_CELL3541_N5': 'Epidermis',
 'c_r1_CELL3542_N3': 'Epidermis',
 'c_r1_CELL3550_N3': 'Epidermis',
 'c_r1_CELL3556_N5': 'Glia',
 'c_r1_CELL3560_N3': 'Muscle somatic',
 'c_r1_CELL3565_N5': 'Epidermis',
 'c_r1_CELL3580_N3': 'Yolk',
 'c_r1_CELL3581_N3': 'Glia lateral',
 'c_r1_CELL3582_N3': 'Neuronal 1',
 'c_r1_CELL3585_N3': 'Sense',

In [35]:
rna.obs['label'] = rna.obs['CellID'].map(anno)
rna.obs

,CellID,G2M.Score,Phase,S.Score,SCT_snn_res.0.5,SCT_snn_res.0.6,cell,clusters_old,cond,nCount_RNA,nCount_SCT,nFeature_RNA,nFeature_SCT,old.ident,orig.ident,rep,seurat_clusters,label
0,c_r1_CELL13_N2,-0.004924,G1,-0.004652,4,1,c_r1_CELL13_N2,1,Control,412.0,486.0,186,182,1,1,c_r1,2,Epidermis
1,c_r1_CELL19_N5,-0.033890,G1,-0.013570,3,4,c_r1_CELL19_N5,4,Control,611.0,577.0,316,306,4,1,c_r1,3,Muscle somatic
2,c_r1_CELL23_N2,-0.039053,G1,-0.013570,9,12,c_r1_CELL23_N2,12,Control,800.0,627.0,365,343,12,1,c_r1,8,Glia
3,c_r1_CELL25_N2,0.007819,S,0.041137,6,5,c_r1_CELL25_N2,5,Control,503.0,502.0,288,277,5,1,c_r1,5,Midgut
4,c_r1_CELL41_N4,-0.030128,S,0.029388,4,1,c_r1_CELL41_N4,1,Control,526.0,509.0,301,286,1,1,c_r1,2,Epidermis
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18488,kd_r2_CELL41467_N1,0.018736,G2M,-0.010234,13,16,kd_r2_CELL41467_N1,16,Mef2EzKD,463.0,483.0,258,241,16,2,kd_r2,12,Salivary Gland
18489,kd_r2_CELL41480_N1,-0.004236,G1,-0.008374,14,8,kd_r2_CELL41480_N1,8,Mef2EzKD,365.0,412.0,253,238,8,2,kd_r2,13,Epidermis head
18490,kd_r2_CELL41485_N1,-0.002440,G1,-0.009304,7,7,kd_r2_CELL41485_N1,7,Mef2EzKD,339.0,427.0,219,211,7,2,kd_r2,6,Fat Body
18491,kd_r2_CELL41564_N1,-0.027476,S,0.013046,4,1,kd_r2_CELL41564_N1,1,Mef2EzKD,267.0,403.0,239,228,1,2,kd_r2,2,Epidermis
18492,kd_r2_CELL41570_N1,0.013650,G2M,-0.007057,7,7,kd_r2_CELL41570_N1,7,Mef2EzKD,221.0,361.0,170,165,7,2,kd_r2,6,Fat Body

In [36]:
rna.write_h5ad('private/data/snRNAseq-nogonad.h5ad')